### ISSUE TITLE
[BUG] Preview images don't update in manage page

### ISSUE THREAD

**Issue by k-veikur** [Nensec/FRTools#12]
When looking at skins in your management page that have had their files updated, the images were never updated and remain what the first upload was like. It's fine when you go to any other page though.

![image](https://user-images.githubusercontent.com/32003188/67523704-83a74d00-f6af-11e9-82b1-94aeb54cf3c8.png)
![image](https://user-images.githubusercontent.com/32003188/67523719-8ace5b00-f6af-11e9-9d61-a1bd1949f357.png)

**Comment by Nensec** [comment]
Oh, right, I fixed this with https://github.com/Nensec/FRTools/commit/c14d3c7271bed947fdf30523cb3c12f00c89c3f7
