### ISSUE TITLE
Unable to login via Discord [BUG]

### ISSUE THREAD

**Issue by Vaycol** [Nensec/FRTools#17]
I have an account on the site that already has a skin uploaded on it, and I am unable to sign back into it. The account is liked to my Discord. Whenever I try to log back in, it asks me to authorize it to access my Discord, even though I have done this already and it is listed in my Authorized Apps. After this, it takes me back to the login screen, along with this message:
System.Linq.Enumerable+WhereSelectArrayIterator`2[System.String,System.String]
I would like to be able to access my account, but the site simply will not let me in.

**Comment by Nensec** [comment]
With the latest feature update, this should now be fixed. I'm sorry it took so long :x
