### ISSUE TITLE
[BUG] Wrong dressing room scry

### ISSUE THREAD

**Issue by gaemar** [Nensec/FRTools#19]
Every time I put in a different dressing room scry, it shows the previous outfit I had planned. 

The link for the dressing room scry i'm using is this
> https://www1.flightrising.com/dgen/dressing-room/dragon?did=62031414&skin=0&apparel=32283,769,23022,12270,29290,28506,28783,28800,28803,28801,1751&xt=dressing.png

This is the current outfit I wish to see the accent on
![image](https://user-images.githubusercontent.com/73424391/97104488-4559ba80-1682-11eb-93be-85003fff069b.png)

This is the old outfit that keeps showing
![image](https://user-images.githubusercontent.com/73424391/97104496-51de1300-1682-11eb-99f8-3fc29978334a.png)

**Comment by Nensec** [comment]
Does this happen on every skin you preview?
If not, can you give me the Id of the skin you are attempting this preview on?

**Comment by gaemar** [comment]
Yes, it seems to be every skin I try to preview.

**Comment by Nensec** [comment]
I think I understand the problem.

The dressing room url you provided has a dragonid in it. My caching strategy right now is to save one set of apparel per dragon, as part of that dragon. So no matter what URL you provide, if it already has a previous version saved that is the one that will be returned. However, you can force the site to generate a new preview. On preview result page there should be a blue bar at the bottom of the page there will tell you this, with a link you can click to force this new generation action.

![image](https://user-images.githubusercontent.com/672037/97113251-5ab5ff80-16e9-11eb-9fa7-804050d6bd5a.png)

Keep in mind that your browser will also cache images, so you might need to CTRL-F5 to _actually_ see the new image. This is something I cannot really easily fix at this moment but it is on my radar.

**Comment by gaemar** [comment]
I tried manually forcing it by clicking the bottom link and CTRL-F5 and it still shows the old version. I've also cleared my cache to see if it my chrome being wonky. Thank you anyway!
